### ISSUE TITLE
Upload more references and alignments of 88kb plasmid

### ISSUE THREAD

**Issue by MauroDiGirolamo** [imgag/ProgrammierPraktikum2018_Gruppe3#11]
Kind reminder that you wanted to do this.

**Comment by caspargross** [comment]
[Link](https://gigamove.rz.rwth-aachen.de/d/id/udbr5Acb4GTrEw)

[Description](https://github.com/imgag/ProgrammierPraktikum2018_Gruppe3/wiki/Example_Data#additional-plasmid-dataset)
