### ISSUE TITLE
Create long read alignment with Minimap2

### ISSUE THREAD

**Issue by caspargross** [imgag/ProgrammierPraktikum2018_Gruppe3#3]
- [x] Map FastQ File with reads to reference
- [x] Sort and Index with SAMTOOLS
- [x] View resulting BamFile

Find a way to execute these external tools from Java (Linux only)

**Comment by caspargross** [comment]
- [ ] Adjust number of threads (n-1)
- [ ] Run in separate thread, independent to JavaFX
https://docs.oracle.com/javase/8/javafx/interoperability-tutorial/concurrency.htm

**Comment by MauroDiGirolamo** [comment]
https://github.com/imgag/ProgrammierPraktikum2018_Gruppe3/commit/c74e19bf0fbec1bbe77f1872eb1dc0b5b30bbed1
