### ISSUE TITLE
Determine referencevoverlaps and identify start positions of mapped reads

### ISSUE THREAD

**Issue by caspargross** [imgag/ProgrammierPraktikum2018_Gruppe3#8]
* Some references (p5.fasta) may have overlapping ends (GC)
* Some reads, especially when starting with homopolymers, dont start at position 1 even though they are circular. 
- [x] Extract starting/end positions of reads
- [x] Plot positions in histogram (JavaFX) 0:20 (n-20):n
- [x] Think about algorithmic solutions

**Comment by caspargross** [comment]
- [ ] Upload more references and alignments of 88kb plasmid (caspar)

**Comment by MauroDiGirolamo** [comment]
https://github.com/imgag/ProgrammierPraktikum2018_Gruppe3/commit/537460c1453800ae0620035dbf86706805543fd5
